server {
  listen 80;
  listen [::]:80;
  root /srv/www/static;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  resolver 127.0.0.11 valid=30s;

  location / {
    set $upstream_frontend frontend;
    proxy_pass http://$upstream_frontend:5174;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_cache_bypass $http_upgrade;
  }

  location /static {
    alias /srv/www/static;
    index  index.html index.htm;
    expires 30d;
    add_header Cache-Control "public, max-age=2592000";
  }

  location /node/ {
    set $upstream_node nodejs;
    rewrite ^/node/(.*)$ /$1 break;
    proxy_pass http://$upstream_node:3000;
  }

  location /notification/ {
    set $upstream_notification notification;
    rewrite ^/notification/(.*)$ /$1 break;
    proxy_pass http://$upstream_notification:3000;
  }

  location /php/ {
      set $upstream_php php;
      rewrite ^/php/(.*)$ /$1 break;
      proxy_pass http://$upstream_php:80;
  }

  location /auth/ {
    set $upstream_keycloak keycloak;
    proxy_pass http://$upstream_keycloak:8080;
  }

}
